import { Inter } from "next/font/google";
import "./globals.css";
const inter = Inter({ subsets: ["latin"] });
import AppContextProvider from "@/context/AppContext";
import Header from "./header/page";
export const metadata={
  title: "SatyamEstate",
  description: "Generated by create next app",
};
export default function RootLayout({children}){
  return (
    <html lang="en">
      <body className={inter.className}>
      <AppContextProvider>
        <div className="h-[100vh] w-[100vw] relative">
        <Header/>
        {children}
        </div>
      </AppContextProvider>
      </body>
    </html>
  );
}
