import mongoose from "mongoose";
const listingSchema=new mongoose.Schema({
    name:{
        type:String,
        required:true
    },
    mo:{
        type:String,
        required:true
    },
    address:{
        type:String,
        required:true
    },
    regularPrice:{
        type:Number,
        required:true
    },
    discountedPrice:{
        type:Number,
    },
    bathrooms:{
        type:Number,
        required:true
    },
    bedrooms:{
        type:Number,
        required:true
    },
    furnished:{
        type:Boolean,
        required:true
    },
    parking:{
        type:Boolean,
        required:true
    },
    type:{
        type:String,
        required:true
    },
    offer:{
        type:Boolean,
        default:false
    },
    imageUrls:{
        type:Array,
        required:true
    },
    userRef:{
       type:String,
       required:true
    },
},{timestamps:true})
const Listing=mongoose.models.Listing || mongoose.model("Listing",listingSchema);
export default Listing;